jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/621774486173/locations/global/workloadIdentityPools/github-pool/providers/githubactions
          service_account: cloud-run-deployer@project-906d7388-8b4a-466e-a5b.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: project-906d7388-8b4a-466e-a5b

      - name: Verify authentication
        run: gcloud auth list

# gcloud iam service-accounts add-iam-policy-binding "cloud-run-deployer@project-906d7388-8b4a-466e-a5b.iam.gserviceaccount.com" \
#   --project="project-906d7388-8b4a-466e-a5b" \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="principalSet://iam.googleapis.com/projects/621774486173/locations/global/workloadIdentityPools/github-pool/attribute.repository/abdullah-s-noor/learn-cicd-typescript-starter"

